### PR TITLE
Fix the version verification and add separate image dump argument

### PR DESCRIPTION
**Pull request by tmjd**
## Description

Also include a comment in the code around needing to update the Makefile check if the line changes again.

## For PR author

- [ ] Tests for change.
- [ ] If changing pkg/apis/, run `make gen-files`
- [ ] If changing versions, run `make gen-versions`

## For PR reviewers

A note for code reviewers - all pull requests must have the following:

- [ ] Milestone set according to targeted release.
- [ ] Appropriate labels:
  - `kind/bug` if this is a bugfix.
  - `kind/enhancement` if this is a a new feature.
  - `enterprise` if this PR applies to Calico Enterprise only.

### CODE REVIEW

**Review by ozdanborne — COMMENTED** [review]
When I first saw this error, I thought it was a bug that we were printing all three of the Operator, Calico, and Enterprise versions on the same line. Are you sure we don't want to split that over three lines instead?

**Comment by tmjd** [comment]
I kept it at one line because I thought for purposes of using that output to get the images it would be good to have it all on one line.
That being said maybe we should add a new option for dumping the image list separately, and then splitting those among a few lines wouldn't matter.

**Comment by tmjd** [comment]
Could we do that additional change as a separate PR? That way I can pick this one to the release-v1.14 and cloud-dev and not make "unnecessary" changes on top.

**Comment by tmjd** [comment]
Ok I changed my mind about the "unnecessary" changes and updated this PR.
WDYT?

**Review by ozdanborne — APPROVED** [review]

**Pull request merged**
