### PR TITLE
[release-v1.30] Auto pick #2617: Move BGPFilter permissions from EE-only to OSS+EE in

### PR DESCRIPTION
**Pull request by coutinhop**
Cherry pick of #2617 on release-v1.30.

#2617: Move BGPFilter permissions from EE-only to OSS+EE in

Fixes https://github.com/projectcalico/calico/issues/7715 and https://github.com/tigera/operator/issues/2675

# Original PR Body below

## Description

BGPFilters permissions were only being added to apiserver for EE, but they should be for both OSS+EE, this PR does this.

Fixes https://github.com/projectcalico/calico/issues/7598

## For PR author

- [ ] Tests for change.
- [ ] If changing pkg/apis/, run `make gen-files`
- [ ] If changing versions, run `make gen-versions`

## For PR reviewers

A note for code reviewers - all pull requests must have the following:

- [ ] Milestone set according to targeted release.
- [ ] Appropriate labels:
  - `kind/bug` if this is a bugfix.
  - `kind/enhancement` if this is a a new feature.
  - `enterprise` if this PR applies to Calico Enterprise only.

### CODE REVIEW

**Comment by tmjd** [comment]
It is not in 1.30.2 because this PR was merged after v1.30.2 was created.

**Comment by psy-q** [comment]
Ah, I see. It still has 1.30.2 as a milestone which made me think it would be included.

**Comment by ankitabhopatkar13** [comment]
Thanks for the fix! 

Is this change going to be released anytime soon? It is breaking our ArgoCD integration as well.

**Comment by Kirkland-gh** [comment]
our ArgoCD is also broken due to this bug.

**Comment by dardevelin** [comment]
We can't deploy fast enough to use the workaround, it definitely broke our ability to operate

**Comment by heliochronix** [comment]
My cluster is having issues due to this breaking garbage collection. Looking forward to a release as well!

**Comment by davhdavh** [comment]
are we getting a 3.26.1 release for this?

**Comment by btodoroff** [comment]
Breaks Rancher as well...

**Comment by jodem** [comment]
Fixed it by using 1.30.2 operator version. If you use calico chart just set tigeraOperator.version to v1.30.2.

**Comment by jodem** [comment]
The one liner fix 

kubectl get clusterrole calico-crds -o yaml | yq eval '.rules[2].resources += ["bgpfilters"]' - | kubectl apply -f -

**Comment by jodem** [comment]
Problem is the fix I propose get wiped automatically by the operator, so please release a fixed version quickly, since latest calico chart basically breaks the job deletion and can cause 409 errors when deleting a job through api.

**Pull request merged**
