### PR TITLE
[release-v1.24] Auto pick #1602: Add: disableBGPExport to pkg files

### PR DESCRIPTION
**Pull request by frozenprocess**
Cherry pick of #1602 on release-v1.24.

#1602: Add: disableBGPExport to pkg files

### CODE REVIEW

**Comment by frozenprocess** [comment]
Hey @doublek,
Seems like there is a new feature in libcalico causing `release-v1.24` problems.
This PR helps with the situation.

**Review by doublek — APPROVED** [review]
LGTM

**Comment by marvin-tigera** [comment]
OK, I will merge the pull request when it's ready, leave the commits as is when I merge it, and leave the branch after I've merged it.

**Pull request merged**
