### PR TITLE
Update versions of Calico and Enterprise

### PR DESCRIPTION
**Pull request by doublek**
## For PR author

- [ ] Tests for change.
- [ ] If changing pkg/apis/, run `make gen-files`
- [ ] If changing versions, run `make gen-versions`

## For PR reviewers

A note for code reviewers - all pull requests must have the following:

- [ ] Milestone set according to targeted release.
- [ ] Appropriate labels:
  - `kind/bug` if this is a bugfix.
  - `kind/enhancement` if this is a a new feature.
  - `enterprise` if this PR applies to Calico Enterprise only.

### CODE REVIEW

**Comment by marvin-tigera** [comment]
OK, I will merge the pull request when it's ready, leave the commits as is when I merge it, and delete the branch after I've merged it.

**Review by mgleung — APPROVED** [review]
LGTM

**Review by mgleung — APPROVED** [review]
LGTM

**Review by tmjd — APPROVED** [review]
LGTM, I don't know why CI shows it was stopped. If it was a failure I would kick it to run again but since I don't know why it was stopped I'll leave it to you.

**Comment by marvin-tigera** [comment]
I'm sorry but I failed delete the branch after merging the pull request.

**Pull request merged**
