### PR TITLE
Automated cherry pick of #1840: Test changed to allow master or release branches

### PR DESCRIPTION
**Pull request by rene-dekker**
Cherry pick of #1840 on release-v1.26.

#1840: Test changed to allow master or release branches

### CODE REVIEW

**Comment by marvin-tigera** [comment]
OK, I will merge the pull request when it's ready, leave the commits as is when I merge it, and delete the branch after I've merged it.

**Review by doublek — APPROVED** [review]
LGTM

**Comment by marvin-tigera** [comment]
Removing "merge-when-ready" label due to new commits

**Pull request closed without merging**
