### PR TITLE
Add ClusterServiceVersions

### PR DESCRIPTION
**Pull request by lmm**
## Description

This PR adds the original v1.3.1 CSV and the most recent v1.5.2, v1.5.3 and v1.7.3 CSV's generated with `make gen-csv` and `make gen-bundle`.

However, the v1.7.3 csv has been modified outside of the make targets mentioned above. 4a98598 changes the crds to use apiextensions.k8s.io/v1beta1 so that the bundle will pass upstream validation tests.

## For PR author

- [ ] Tests for change.
- [ ] If changing pkg/apis/, run `make gen-files`
- [ ] If changing versions, run `make gen-versions`

## For PR reviewers

A note for code reviewers - all pull requests must have the following:

- [ ] Milestone set according to targeted release.
- [ ] Appropriate labels:
  - `kind/bug` if this is a bugfix.
  - `kind/enhancement` if this is a a new feature.
  - `enterprise` if this PR applies to Calico Enterprise only.

### CODE REVIEW

**Comment by tmjd** [comment]
Does this need any changes now that we know the certification doesn't support v1 (only v1beta1 currently)?

**Comment by lmm** [comment]
> Does this need any changes now that we know the certification doesn't support v1 (only v1beta1 currently)?

Sorry, I should've made this PR a draft once I got the updated info. Yeah, we may need to make some changes; still TBD though.

**Comment by tmjd** [comment]
I noticed that there are no operator manifest, cluster role, or bindings as part of this. Can you remind me where those come from with OLM?

I'm wondering if we need to look at our tooling to generate the v1beta manifests. Do we have any idea how long we'll need to be using v1beta1 for the CRDs?

**Comment by lmm** [comment]
>I noticed that there are no operator manifest, cluster role, or bindings as part of this. Can you remind me where those come from with OLM?

The operator deployment and rbac manifests are provided as inputs to the CSV generation process: https://github.com/tigera/operator/blob/master/hack/gen-csv/get-manifests.sh#L29-L31

 The operator deployment and rbac are then embedded into the resulting csv.

> I'm wondering if we need to look at our tooling to generate the v1beta manifests. Do we have any idea how long we'll need to be using v1beta1 for the CRDs?

When chatting with @caseydavenport , we were looking at this as just a one-off. I think that is still doable if we are okay with delaying v3.16 certification.

**Comment by lmm** [comment]
Thanks @tmjd !

**Pull request merged**
