### PR TITLE
Fix typo in installation_types

### PR DESCRIPTION
**Pull request by doublek**
## Description

This typo was noticed in autogerated docs. I've also run the various generate targets and nothing else seems to have changed.

## For PR author

- [ ] Tests for change.
- [x] If changing pkg/apis/, run `make gen-files`
- [ ] If changing versions, run `make gen-versions`

## For PR reviewers

A note for code reviewers - all pull requests must have the following:

- [ ] Milestone set according to targeted release.
- [ ] Appropriate labels:
  - `kind/bug` if this is a bugfix.
  - `kind/enhancement` if this is a a new feature.
  - `enterprise` if this PR applies to Calico Enterprise only.

### CODE REVIEW

**Review by lmm — APPROVED** [review]
LGTM

**Comment by marvin-tigera** [comment]
OK, I will merge the pull request when it's ready, leave the commits as is when I merge it, and leave the branch after I've merged it.

**Comment by caseydavenport** [comment]
@doublek I think this needs a `make gen-files`

**Pull request closed without merging**
