### PR TITLE
Automatic version updates for v1.32.4 release

### PR DESCRIPTION
**Pull request by radTuti**
## Description

Prepare to release v1.32.4

## For PR author

- [x] Tests for change.
- [x] If changing pkg/apis/, run `make gen-files`
- [x] If changing versions, run `make gen-versions`

## For PR reviewers

A note for code reviewers - all pull requests must have the following:

- [ ] Milestone set according to targeted release.
- [ ] Appropriate labels:
  - `kind/bug` if this is a bugfix.
  - `kind/enhancement` if this is a a new feature.
  - `enterprise` if this PR applies to Calico Enterprise only.

### CODE REVIEW

**Comment by marvin-tigera** [comment]
OK, I will merge the pull request when it's ready, squash the commits when I merge it, and delete the branch after I've merged it.

**Review by rene-dekker — APPROVED** [review]
lgtm

**Comment by radTuti** [comment]
closing this as it is incorrect

**Pull request closed without merging**
