### PR TITLE
Add pull policy explicitly

### PR DESCRIPTION
**Pull request by caseydavenport**
## Description

Spell out the pull policy explicitly - we might want to make this configurable anyway, but for now just set the values to the default. 

## For PR author

- [ ] Tests for change.
- [ ] If changing pkg/apis/, run `make gen-files`
- [ ] If changing versions, run `make gen-versions`

## For PR reviewers

A note for code reviewers - all pull requests must have the following:

- [ ] Milestone set according to targeted release.
- [ ] Appropriate labels:
  - `kind/bug` if this is a bugfix.
  - `kind/enhancement` if this is a a new feature.
  - `enterprise` if this PR applies to Calico Enterprise only.

### CODE REVIEW

**Comment by rene-dekker** [comment]
I was wondering if we could - similar to `common.OperatorNamespace()` - have a method to set them all and respond to env if it exists. Would be great for dev / test type of stuff.

**Comment by caseydavenport** [comment]
@tmjd @rene-dekker added a couple tests - LMK what you think

**Review by tmjd — APPROVED** [review]
LGTM

**Comment by marvin-tigera** [comment]
OK, I will merge the pull request when it's ready, squash the commits when I merge it, and delete the branch after I've merged it.

**Comment by marvin-tigera** [comment]
Removing "merge-when-ready" label due to new commits

**Pull request merged**
