### PR TITLE
Bump Enterprise versions to v3.2.1.

### PR DESCRIPTION
**Pull request by stevegaossou**
## Description
- Update Enterprise versions to v3.2.1

## For PR author

- [ ] Tests for change.
- [ ] If changing pkg/apis/, run `make gen-files`
- [ ] If changing versions, run `make gen-versions`

## For PR reviewers

A note for code reviewers - all pull requests must have the following:

- [ ] Milestone set according to targeted release.
- [ ] Appropriate labels:
  - `kind/bug` if this is a bugfix.
  - `kind/enhancement` if this is a a new feature.
  - `enterprise` if this PR applies to Calico Enterprise only.

### CODE REVIEW

**Review by doublek — APPROVED** [review]
LGTM

**Review by doublek — CHANGES_REQUESTED** [review]
Actually we should bump calico components to v3.15.3

**Comment by stevegaossou** [comment]
@doublek it's ready for another look.

**Review by bcreane — APPROVED** [review]
looks good.

**Pull request merged**
