### PR TITLE
Fix CI: `make gen-versions` and committed

### PR DESCRIPTION
**Pull request by rene-dekker**
Did `make gen-versions` and committed

### CODE REVIEW

**Review by caseydavenport — APPROVED** [review]

**Comment by marvin-tigera** [comment]
OK, I will merge the pull request when it's ready, leave the commits as is when I merge it, and delete the branch after I've merged it.

**Comment by tmjd** [comment]
I think the CI here would have been helped with #1710. I'll kick CI to rerun.

**Comment by marvin-tigera** [comment]
I'm sorry but I failed delete the branch after merging the pull request.

**Pull request merged**
