### PR TITLE
[cherry-pick] updating envoy config to have nodeports listener

### PR DESCRIPTION
**Pull request by penkeysuresh**
## For PR author

- [ ] Tests for change.
- [ ] If changing pkg/apis/, run `make gen-files`
- [ ] If changing versions, run `make gen-versions`

## For PR reviewers

A note for code reviewers - all pull requests must have the following:

- [ ] Milestone set according to targeted release.
- [ ] Appropriate labels:
  - `kind/bug` if this is a bugfix.
  - `kind/enhancement` if this is a a new feature.
  - `enterprise` if this PR applies to Calico Enterprise only.

### CODE REVIEW

**Review by doublek — APPROVED** [review]
LGTM

**Comment by tmjd** [comment]
You might need to rebase your branch. I thought Rob had already updated the UI settings CRD that this is erroring on.

**Comment by penkeysuresh** [comment]
These changes are already present in[ v1.25,](https://github.com/tigera/operator/blob/release-v1.25/pkg/render/applicationlayer/envoy-config.yaml.template#L125-L141) they are likely picked from master as a part of https://github.com/tigera/operator/pull/1739 and then cherry picked into v1.25, closing this for that reason

**Comment by penkeysuresh** [comment]
Need to re-open this commit as the previous one that contained the nodeport fix is being reverted through https://github.com/tigera/operator/pull/1778

**Pull request merged**
