### PR TITLE
Update versions for v1.22

### PR DESCRIPTION
**Pull request by Brian-McM**
## For PR author

- [ ] Tests for change.
- [ ] If changing pkg/apis/, run `make gen-files`
- [ ] If changing versions, run `make gen-versions`

## For PR reviewers

A note for code reviewers - all pull requests must have the following:

- [x] Milestone set according to targeted release.
- [ ] Appropriate labels:
  - `kind/bug` if this is a bugfix.
  - `kind/enhancement` if this is a a new feature.
  - `enterprise` if this PR applies to Calico Enterprise only.

### CODE REVIEW

**Review by doublek — APPROVED** [review]
LGTM

**Comment by stevehipwell** [comment]
@Brian-McM I'm interested as to why the operator v1.21 and v1.22 releases are both targeting Calico v3.20.0 and the operator v1.20 release is targeting the newer Calico v3.20.1?

**Comment by Brian-McM** [comment]
@stevehipwell I think it was just a combination of the Calico patch coming out after the release (for v1.21) and me not updating to use the patch release after I'd created the release branch (for v1.22).

There's a patch release that was created for v1.21 after Calico 3.20.1 but it may have been targeting either an operator specific fix or a Calico Enterprise fix, in which case the version of Calico may not have been considered.

**Comment by stevehipwell** [comment]
@Brian-McM is it worth patching v1.21 and v1.22 so they at least have the same version as the latest v1.20 release?

For completeness and to limit unwanted churn when upgrading the operator I'd suggest that this should be done. But I bet there are other considerations against this?

**Pull request merged**
