### PR TITLE
Automated cherry pick of #1523: Add resource quota to components

### PR DESCRIPTION
**Pull request by doublek**
Cherry pick of #1523 on release-v1.22.

#1523: Add resource quota to components

### CODE REVIEW

**Review by tmjd — APPROVED** [review]
LGTM once CI is done

**Comment by marvin-tigera** [comment]
OK, I will merge the pull request when it's ready, leave the commits as is when I merge it, and delete the branch after I've merged it.

**Comment by marvin-tigera** [comment]
I'm sorry but I failed delete the branch after merging the pull request.

**Pull request merged**
