### PR TITLE
Add controller dependency graph

### PR DESCRIPTION
**Pull request by hjiawei**
Add a dependency graph between different controllers in operator. This
is by analyzing the `Reconcile()` function in each controller. It is
part of the work from Operator Managed Prometheus.

This graph is generated using the python binding for graphviz. It is
still a manual process to update and regenerate the graph using the
python script `generate-controller-dependency-graph.py` at the moment.

## For PR author

- [ ] Tests for change.
- [ ] If changing pkg/apis/, run `make gen-files`
- [ ] If changing versions, run `make gen-versions`

## For PR reviewers

A note for code reviewers - all pull requests must have the following:

- [ ] Milestone set according to targeted release.
- [ ] Appropriate labels:
  - `kind/bug` if this is a bugfix.
  - `kind/enhancement` if this is a a new feature.
  - `enterprise` if this PR applies to Calico Enterprise only.

### CODE REVIEW

**Comment by hjiawei** [comment]
This is a doc only change. No real code changes.

- I can find a better place for the dependency graph if it doesn't belong here.
- ClusterController (ManagementCluster and ManagementClusterConnection) is tricky to draw. Please suggest a better way to visualise it.
- I am also open to suggestions on the tool to generate the graph.

**Comment by stevegaossou** [comment]
Does it make sense to have the source that the graph is generated from? It will make re-generating the dependency graph in the future easy and therefore increase the chances we'll keep the graph up-to-date (e.g. when Monitor is added).

**Comment by hjiawei** [comment]
@stevegaossou Good point. Let me find a proper tool to generate the graph.

**Comment by matthewdupre** [comment]
FYI https://github.com/hjiawei/operator/tree/controller-dependency-graph#controller-dependency-graph will show you the image

**Comment by hjiawei** [comment]
Updated to reflect the latest changes in: https://github.com/tigera/operator/pull/1306

**Review by tmjd — APPROVED** [review]
LGTM

**Pull request merged**
