### PR TITLE
Upgrade Prometheus to v2.42.0

### PR DESCRIPTION
**Pull request by hjiawei**
## Description

This changeset upgrades Prometheus CRDs and version to v2.42.0. It also upgrades `kindest/node` to the latest v1.21 and `kubectl` to the latest v1.25 releaes trains for FVs.

## For PR author

- [ ] Tests for change.
- [x] If changing pkg/apis/, run `make gen-files`
- [x] If changing versions, run `make gen-versions`

## For PR reviewers

A note for code reviewers - all pull requests must have the following:

- [ ] Milestone set according to targeted release.
- [ ] Appropriate labels:
  - `kind/bug` if this is a bugfix.
  - `kind/enhancement` if this is a a new feature.
  - `enterprise` if this PR applies to Calico Enterprise only.

### CODE REVIEW

**Comment by hjiawei** [comment]
This image is tested in a gcp-kubeadm cluster with Calico Enterprise v3.16 pre pre-release.

**Review by dimitri-nicolo — APPROVED** [review]
lgtm

**Comment by hjiawei** [comment]
This PR also fixes https://github.com/tigera/operator/issues/2465.

**Review by rene-dekker — APPROVED** [review]
lgtm

**Pull request merged**
