### PR TITLE
s390x: build s390x binary and image

### PR DESCRIPTION
**Pull request by huoqifeng**
## Description

Backport https://github.com/tigera/operator/pull/2604 to release v1.30

## For PR author

- [ ] Tests for change.
- [ ] If changing pkg/apis/, run `make gen-files`
- [ ] If changing versions, run `make gen-versions`

## For PR reviewers

A note for code reviewers - all pull requests must have the following:

- [ ] Milestone set according to targeted release.
- [ ] Appropriate labels:
  - `kind/bug` if this is a bugfix.
  - `kind/enhancement` if this is a a new feature.
  - `enterprise` if this PR applies to Calico Enterprise only.

### CODE REVIEW

**Review by mgleung — APPROVED** [review]

**Comment by huoqifeng** [comment]
I think we need release notes to mention s390x supported after this PR merged?

**Comment by mgleung** [comment]
@huoqifeng Yup, you are right and we usually write them from the titles of the PRs when they're tagged for a release note.

@danudey how do you want to handle this?

**Comment by danudey** [comment]
@mgleung If we have a few explicitly-written PR notes we can incorporate those at the top of the release notes to call them out specifically. Would that make sense?

**Pull request merged**
