### PR TITLE
Fix environment name

### PR DESCRIPTION
**Pull request by robbrockbank**
## For PR author

- [ ] Tests for change.
- [ ] If changing pkg/apis/, run `make gen-files`
- [ ] If changing versions, run `make gen-versions`

## For PR reviewers

A note for code reviewers - all pull requests must have the following:

- [ ] Milestone set according to targeted release.
- [ ] Appropriate labels:
  - `kind/bug` if this is a bugfix.
  - `kind/enhancement` if this is a a new feature.
  - `enterprise` if this PR applies to Calico Enterprise only.

### CODE REVIEW

**Review by doublek — APPROVED** [review]
LGTM

**Comment by marvin-tigera** [comment]
OK, I will merge the pull request when it's ready, leave the commits as is when I merge it, and leave the branch after I've merged it.

**Review by tmjd — APPROVED** [review]
LGTM
I'm approving to see if that gets marvin to merge this.
Or is this blocked by the non-required test?

**Comment by doublek** [comment]
@tmjd Indeed looks like it's blocked by a non required test. cc @Brian-McM

**Comment by Brian-McM** [comment]
@doublek @tmjd Marvin only merges if all checks, required or not required, pass. This is intentional and is a safety precaution to prevent Marvin from merging on a project that doesn't have the required checks set up correctly.

It looks like you've hit that docker hub limit, I'd suggest somebody continue the migration to semaphore v2, seems like the build step has been migrated.

**Pull request merged**
