### PR TITLE
Fix CSI node driver resource config

### PR DESCRIPTION
**Pull request by caseydavenport**
## Description

Finishes off this abandoned PR: https://github.com/tigera/operator/pull/2768

Fixes https://github.com/projectcalico/calico/issues/8400

## For PR author

- [ ] Tests for change.
- [ ] If changing pkg/apis/, run `make gen-files`
- [ ] If changing versions, run `make gen-versions`

## For PR reviewers

A note for code reviewers - all pull requests must have the following:

- [ ] Milestone set according to targeted release.
- [ ] Appropriate labels:
  - `kind/bug` if this is a bugfix.
  - `kind/enhancement` if this is a a new feature.
  - `enterprise` if this PR applies to Calico Enterprise only.

### CODE REVIEW

**Review by rene-dekker — APPROVED** [review]
lgtm

**Comment by mashiofu-cafex** [comment]
I am on helm-chart Calico `projectcalico/tigera-operator v3.28.0` and I am still unable to set `csiNodeDriverDaemonSet` memory & limit resources. When applying this configuration the chart is detecting the changes and seems to be updated but I do not see the changes applied. All logs look normal, please see config below:

```    
csiNodeDriverDaemonSet: #Currently an issue and PR open to allow these values to be supported - https://github.com/projectcalico/calico/issues/8400
        spec:
            template:
                spec:
                    containers:
                    - name: csi-node-driver
                      resources:
                        limits:
                            memory: 100Mi
                        requests:
                            cpu: 75m
```

**Comment by evgeny-goldin** [comment]
Same here, we're using https://raw.githubusercontent.com/projectcalico/calico/v3.28.0/manifests/tigera-operator.yaml
and this Installation 

```
apiVersion: operator.tigera.io/v1
kind: Installation
metadata:
  name: default
spec:
  csiNodeDriverDaemonSet:
    spec:
      template:
        spec:
          containers:
            - name: calico-csi
              resources:
                limits:
                  memory: 10Mi
                requests:
                  cpu: 10m
                  memory: 10Mi
            - name: csi-node-driver-registrar
              resources:
                limits:
                  memory: 20Mi
                requests:
                  cpu: 10m
                  memory: 20Mi
```

triggers this error when applying it

```
one or more objects failed to apply, reason: Installation.operator.tigera.io "default" is invalid: [spec.csiNodeDriverDaemonSet.spec.template.spec.containers[0].name: Unsupported value: "calico-csi": supported values: "csi-node-driver", spec.csiNodeDriverDaemonSet.spec.template.spec.containers[1].name: Unsupported value: "csi-node-driver-registrar": supported values: "csi-node-driver"]
```

@rene-dekker, @caseydavenport

**Comment by tmjd** [comment]
Fixes #2412

**Pull request merged**
