### PR TITLE
[release-v1.31] Increase probes timeout for calico components

### PR DESCRIPTION
**Pull request by hjiawei**
## Description

This changeset increases k8s liveness and readiness probe period and timeout for various Calico components. Before this change, most of the components are using k8s default `TimeoutSeconds` (1s) and `PeriodSeconds` (10s). These defaults cause some components to become unhealthy quickly and got restarted by k8s engine, especially under a busy cluster or with long running tasks.

We have tuned period and timeout seconds as follows:
* liveness probe: bump timeout to 5s and period to 60s. One component will be restarted after it fails to response for 3 minutes (with default `FailureThreshold` 3).
* readiness probe: bump timeout to 5s and period to 30s. One component will be removed from service after 1.5 minute (with default `FailureThreshold` 3).
* certain components (like fluentd or elasticsearch) will have a longer timeout, period, and/or failure threshold.

Pick https://github.com/tigera/operator/pull/2746 into release v1.31 branch.

## For PR author

- [ ] Tests for change.
- [ ] If changing pkg/apis/, run `make gen-files`
- [ ] If changing versions, run `make gen-versions`

## For PR reviewers

A note for code reviewers - all pull requests must have the following:

- [ ] Milestone set according to targeted release.
- [ ] Appropriate labels:
  - `kind/bug` if this is a bugfix.
  - `kind/enhancement` if this is a a new feature.
  - `enterprise` if this PR applies to Calico Enterprise only.

### CODE REVIEW

**Review by rene-dekker — APPROVED** [review]
lgtm

**Comment by marvin-tigera** [comment]
OK, I will merge the pull request when it's ready, leave the commits as is when I merge it, and delete the branch after I've merged it.

**Comment by marvin-tigera** [comment]
I'm sorry but I failed delete the branch after merging the pull request.

**Pull request merged**
