### PR TITLE
Fix syslog forwarding volume

### PR DESCRIPTION
**Pull request by rene-dekker**
Pick of 744fb45088

Original pull request: #2120

### CODE REVIEW

**Review by tmjd — APPROVED** [review]
LGTM

**Comment by marvin-tigera** [comment]
OK, I will merge the pull request when it's ready, leave the commits as is when I merge it, and delete the branch after I've merged it.

**Comment by marvin-tigera** [comment]
I'm sorry but I failed delete the branch after merging the pull request.

**Pull request merged**
