### PR TITLE
Support Power image

### PR DESCRIPTION
**Pull request by yussufsh**
Signed-off-by: Yussuf Shaikh <yussuf.shaikh1@ibm.com>

## For PR author

- [ ] Tests for change.
- [ ] If changing pkg/apis/, run `make gen-files`
- [ ] If changing versions, run `make gen-versions`

## For PR reviewers

A note for code reviewers - all pull requests must have the following:

- [ ] Milestone set according to targeted release.
- [ ] Appropriate labels:
  - `kind/bug` if this is a bugfix.
  - `kind/enhancement` if this is a a new feature.
  - `enterprise` if this PR applies to Calico Enterprise only.

### CODE REVIEW

**Comment by mkumatag** [comment]
cc @caseydavenport @tmjd

**Review by caseydavenport — APPROVED** [review]

**Comment by mkumatag** [comment]
@caseydavenport is it possible to cherrypick this fix for the 1.27.x release?

**Comment by caseydavenport** [comment]
@mkumatag yep, can do - care to open a PR and I can merge it?

**Comment by yussufsh** [comment]
> > @mkumatag yep, can do - care to open a PR and I can merge it?
> 
> @yussufsh let's do that..

Done.

**Pull request merged**
