### PR TITLE
Cherry pick #1600 to release-v1.26

### PR DESCRIPTION
**Pull request by freecaykes**
## Description

https://github.com/tigera/operator/pull/1600

## For PR author

- [ ] Tests for change.
- [ ] If changing pkg/apis/, run `make gen-files`
- [ ] If changing versions, run `make gen-versions`

## For PR reviewers

A note for code reviewers - all pull requests must have the following:

- [ ] Milestone set according to targeted release.
- [ ] Appropriate labels:
  - `kind/bug` if this is a bugfix.
  - `kind/enhancement` if this is a a new feature.
  - `enterprise` if this PR applies to Calico Enterprise only.

### CODE REVIEW

**Review by doublek — APPROVED** [review]
LGTM

**Comment by freecaykes** [comment]
dependent on https://github.com/tigera/operator/pull/1836

**Comment by marvin-tigera** [comment]
OK, I will merge the pull request when it's ready, leave the commits as is when I merge it, and delete the branch after I've merged it.

**Review by doublek — APPROVED** [review]
LGTM

**Comment by marvin-tigera** [comment]
I'm sorry but I failed delete the branch after merging the pull request.

**Pull request merged**
